### ISSUE TITLE
Config broke with latest TShock

### ISSUE THREAD

**Issue by Kojirremer** [Quinci135/SEconomy#3]
SEconomy, among many other plugins, broke with changes introduced on TShock for 1.4.2.x. I don't know if it's the same here, but other plugins have changed
`TShock.Config.` for `TShock.Config.Settings.`

Here is the error from the log:
`2021-04-18 23:03:09 - Command: ERROR: System.MissingMethodException: Método no encontrado: 'TShockAPI.ConfigFile TShockAPI.TShock.get_Config()'.
   en Wolfje.Plugins.SEconomy.SEconomyPlugin.<TShock_CommandExecuted>d__29.MoveNext()
   en System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en Wolfje.Plugins.SEconomy.SEconomyPlugin.TShock_CommandExecuted(CommandArgs args)
   en TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)`

**Comment by Quinci135** [comment]
A version of essentials+ is up to date, by the original maintainer https://github.com/QuiCM/EssentialsPlus

Config reference is fixed with d255cec2d40358cd14bae688b5d3fecd457d8704
Since you have a Spanish localization manually edited in, you may just want to use your own files and edit to match:
1. Move the latest TShockAPI.dll, OTAPI.dll, TerrariaServer.exe into the References folder
2. Do Ctrl + Shift + F and Find & Replace
Find: `TShock.Config.`
Replace: `TShock.Config.Settings.`
3. Build
4. Take `.dll` files out of `PluginFolder/bin/DebugOrRelease(whichever is your build configuration, doesn't really matter) and put into your `ServerPlugins` folder

**Comment by Kojirremer** [comment]
Thanks a lot. I have no issue with E+ though, only SEconomy and PermabuffsV2.
Will try the fixes on PermabuffsV2 when I get home.

Thanks again.
